# AdForge one-line installer for Windows (PowerShell)
# Usage from any PowerShell window:
#   iwr -useb https://raw.githubusercontent.com/IamRamgarhia/AdForge-/main/install.ps1 | iex
#
# Does everything in one go:
#   1. Checks for Node.js + git (installs via winget if missing)
#   2. Clones AdForge into %USERPROFILE%\AdForge
#   3. Runs npm install
#   4. Prompts for port (default 3005)
#   5. Launches the launcher control panel in your browser

$ErrorActionPreference = "Stop"

function Write-Step($msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-OK($msg)   { Write-Host "OK  $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "!!  $msg" -ForegroundColor Yellow }
function Write-Err($msg)  { Write-Host "ERR $msg" -ForegroundColor Red }

Write-Host ""
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host " AdForge installer - by Dicecodes" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

# --- Defaults ---
$Repo    = "https://github.com/IamRamgarhia/AdForge-.git"
$Branch  = "main"
$Target  = Join-Path $env:USERPROFILE "AdForge"

# --- Step 1: Node.js ---
Write-Step "Checking for Node.js"
$node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node) {
    Write-Warn "Node.js not found."
    $winget = Get-Command winget -ErrorAction SilentlyContinue
    if ($winget) {
        Write-Host "Installing Node.js LTS via winget..."
        winget install -e --id OpenJS.NodeJS.LTS --accept-package-agreements --accept-source-agreements
        # Refresh PATH for current session
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        $node = Get-Command node -ErrorAction SilentlyContinue
    }
    if (-not $node) {
        Write-Err "Node.js could not be installed automatically."
        Write-Host "  Install it from https://nodejs.org/en/download then re-run this installer."
        exit 1
    }
}
$nodeVer = & node --version
Write-OK "Node $nodeVer"

# --- Step 2: Git ---
Write-Step "Checking for git"
$git = Get-Command git -ErrorAction SilentlyContinue
if (-not $git) {
    Write-Warn "git not found."
    $winget = Get-Command winget -ErrorAction SilentlyContinue
    if ($winget) {
        Write-Host "Installing Git via winget..."
        winget install -e --id Git.Git --accept-package-agreements --accept-source-agreements
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        $git = Get-Command git -ErrorAction SilentlyContinue
    }
    if (-not $git) {
        Write-Err "git could not be installed automatically."
        Write-Host "  Install it from https://git-scm.com/download/win then re-run this installer."
        exit 1
    }
}
Write-OK ("git " + (& git --version))

# --- Step 3: Clone (or update) ---
Write-Step "Fetching AdForge into $Target"
if (Test-Path $Target) {
    if (Test-Path (Join-Path $Target ".git")) {
        Write-Host "Existing checkout found. Pulling latest..."
        Push-Location $Target
        try { & git pull --ff-only } catch { Write-Warn "git pull failed; continuing with existing files." }
        Pop-Location
    } else {
        Write-Warn "$Target exists and is not a git repo. Using folder as-is."
    }
} else {
    & git clone --depth=1 --branch $Branch $Repo $Target
}
Set-Location $Target
Write-OK "Source ready at $Target"

# --- Step 4: npm install ---
Write-Step "Installing dependencies (first run can take a few minutes)"
& npm install --no-audit --no-fund
if ($LASTEXITCODE -ne 0) {
    Write-Err "npm install failed. Read the error above and try again."
    exit 1
}
Write-OK "Dependencies installed"

# --- Step 5: Pick a port ---
Write-Step "Choose a port for the web app"
Write-Host "Common ports: 3000, 3005, 4000, 8080. Press Enter for 3005."
$port = "3005"
if (Test-Path ".env.local") {
    $existing = (Select-String -Path ".env.local" -Pattern "^PORT=" -SimpleMatch:$false | Select-Object -First 1)
    if ($existing) {
        $port = ($existing.Line -replace "^PORT=", "").Trim()
        Write-Host "Found existing PORT=$port in .env.local"
    }
}
$userPort = Read-Host "Port [$port]"
if ($userPort) { $port = $userPort.Trim() }

# Validate
if (-not ($port -match '^\d+$')) { Write-Warn "Not a number. Using 3005."; $port = "3005" }
$portNum = [int]$port
if ($portNum -lt 1024 -or $portNum -gt 65535) { Write-Warn "Out of range. Using 3005."; $port = "3005" }

# Write .env.local
$envBody = @"
# AdForge configuration (generated by install.ps1)
PORT=$port
ADFORGE_SYNC_PORT=3006
"@
Set-Content -Path ".env.local" -Value $envBody -Encoding utf8

if (-not (Test-Path "data")) { New-Item -ItemType Directory -Path "data" | Out-Null }
Write-OK "Saved PORT=$port to .env.local"

# --- Step 6: Launch ---
Write-Host ""
Write-Host "==================================================" -ForegroundColor Green
Write-Host " Install complete - launching AdForge..." -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Launcher (control panel): http://127.0.0.1:3006/"
Write-Host "  Web app (after Start):    http://localhost:$port/"
Write-Host ""
Write-Host "  Click 'Start AdForge' in the launcher when it opens."
Write-Host "  Close this window or run  stop.bat  to shut down."
Write-Host ""

# Open launcher in default browser after a short delay
Start-Job -ScriptBlock {
    Start-Sleep -Seconds 2
    Start-Process "http://127.0.0.1:3006/"
} | Out-Null

# Run sidecar in foreground so Ctrl+C cleanly stops it
$env:ADFORGE_SYNC_PORT = "3006"
& node "scripts\local-sync.cjs"
