@echo off
REM AdForge one-click installer for Windows.
REM Double-click this file. It will:
REM   1. Verify Node.js is installed
REM   2. Run `npm install`
REM   3. Ask which port you want (default 3005) and save to .env.local
REM   4. Print next-step instructions

setlocal EnableDelayedExpansion
cd /d "%~dp0"

echo.
echo ==================================================
echo  AdForge installer
echo  by Dicecodes
echo ==================================================
echo.

REM --- Step 1: Node.js ---
echo Checking for Node.js...
where node >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Node.js is not installed.
    echo.
    echo Download and install Node.js 20 or newer from:
    echo   https://nodejs.org/en/download
    echo.
    echo Then double-click install.bat again.
    echo.
    pause
    exit /b 1
)
for /f "tokens=*" %%v in ('node --version') do set NODE_VER=%%v
echo Found Node %NODE_VER%
echo.

REM --- Step 2: Install dependencies ---
echo Installing dependencies (this may take a few minutes the first time)...
echo.
call npm install --no-audit --no-fund
if errorlevel 1 (
    echo.
    echo [ERROR] npm install failed. Read the error above.
    echo.
    pause
    exit /b 1
)

REM --- Step 3: Configure port ---
echo.
echo ==================================================
echo  Pick a port for the web app.
echo ==================================================
echo.
echo The web app needs an open port on your machine.
echo Common ports: 3000, 3005, 4000, 8080.
echo If you have nothing else running, just press Enter for 3005.
echo.

set "PORT=3005"
if exist .env.local (
    for /f "tokens=2 delims==" %%a in ('findstr /b "PORT=" .env.local 2^>nul') do set "PORT=%%a"
    echo Existing .env.local found. Current PORT=!PORT!
)

set /p USERPORT="Port [%PORT%]: "
if not "!USERPORT!"=="" set "PORT=!USERPORT!"

REM Validate it's numeric and in valid range
echo !PORT!| findstr /r "^[0-9][0-9]*$" >nul
if errorlevel 1 (
    echo [WARN] "%PORT%" is not a number. Falling back to 3005.
    set "PORT=3005"
)
if !PORT! lss 1024 (
    echo [WARN] Ports under 1024 need admin privileges. Falling back to 3005.
    set "PORT=3005"
)
if !PORT! gtr 65535 (
    echo [WARN] Port must be under 65536. Falling back to 3005.
    set "PORT=3005"
)

REM Write .env.local
(
echo # AdForge configuration ^(generated by install.bat^)
echo PORT=!PORT!
echo ADFORGE_SYNC_PORT=3006
) > .env.local

REM Make sure data folder exists
if not exist data mkdir data

echo.
echo Saved PORT=!PORT! to .env.local
echo.

REM --- Create Desktop shortcut to AdForge.bat ---
echo Creating Desktop shortcut...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$d = [Environment]::GetFolderPath('Desktop');" ^
  "$t = Join-Path '%CD%' 'AdForge.bat';" ^
  "$s = (New-Object -ComObject WScript.Shell).CreateShortcut((Join-Path $d 'AdForge.lnk'));" ^
  "$s.TargetPath = $t; $s.WorkingDirectory = '%CD%'; $s.Description = 'Launch AdForge'; $s.WindowStyle = 7; $s.Save();" ^
  "Write-Host ('  -> ' + (Join-Path $d 'AdForge.lnk'))"

echo.
echo ==================================================
echo  Install complete.
echo ==================================================
echo.
echo Next steps:
echo   1. Double-click  AdForge  on your Desktop  ^(or AdForge.bat in this folder^)
echo   2. Your browser opens to the AdForge launcher
echo   3. Click the orange Start button to boot the web app
echo.
echo You can also open these directly in your browser once Start has been clicked:
echo        http://localhost:!PORT!/
echo        http://adforge.localhost:!PORT!/    ^(zero setup, works in all modern browsers^)
echo.
echo Your data lives in:
echo   %CD%\data\snapshot.json
echo Zip this folder to move AdForge + your work to another machine.
echo.
pause
