#!/usr/bin/env bash
# AdForge one-click installer for Mac / Linux.
# Run:  bash install.sh

set -e
cd "$(dirname "$0")"

echo
echo "=================================================="
echo " AdForge installer"
echo " by Dicecodes"
echo "=================================================="
echo

if ! command -v node >/dev/null 2>&1; then
  echo "[ERROR] Node.js is not installed."
  echo
  echo "Install Node 20+ from https://nodejs.org/en/download"
  echo "Or with a version manager:"
  echo "    macOS:        brew install node"
  echo "    Ubuntu/Deb:   sudo apt install nodejs npm"
  echo "    nvm:          nvm install 20 && nvm use 20"
  echo
  exit 1
fi

NODE_VER=$(node --version)
echo "Found Node $NODE_VER"
echo

echo "Installing dependencies (this may take a few minutes the first time)..."
echo
npm install --no-audit --no-fund

mkdir -p data
chmod +x AdForge.command scripts/start.sh scripts/stop.sh scripts/set-domain.sh 2>/dev/null || true

# Try to create a Desktop shortcut so users can launch with one click.
if [ -d "$HOME/Desktop" ]; then
  if [ "$(uname)" = "Darwin" ]; then
    # macOS: copy the .command (Finder runs .command files in Terminal)
    cp -f AdForge.command "$HOME/Desktop/AdForge.command" 2>/dev/null && \
      chmod +x "$HOME/Desktop/AdForge.command" 2>/dev/null && \
      echo "Created Desktop shortcut: ~/Desktop/AdForge.command"
  else
    # Linux: write a .desktop entry
    cat > "$HOME/Desktop/AdForge.desktop" <<DESK
[Desktop Entry]
Type=Application
Name=AdForge
Comment=Local AI ad operations cockpit
Exec=bash $(pwd)/AdForge.command
Terminal=true
Categories=Office;Development;
DESK
    chmod +x "$HOME/Desktop/AdForge.desktop" 2>/dev/null
    echo "Created Desktop shortcut: ~/Desktop/AdForge.desktop"
  fi
fi

echo
echo "=================================================="
echo " Pick a port for the web app."
echo "=================================================="
echo
echo "The web app needs an open port on your machine."
echo "Common ports: 3000, 3005, 4000, 8080."
echo "If you have nothing else running, just press Enter for 3005."
echo

# Pre-fill from existing .env.local if present
DEFAULT_PORT=3005
if [ -f .env.local ]; then
  EXISTING=$(grep -E '^PORT=' .env.local | head -1 | cut -d= -f2)
  if [ -n "$EXISTING" ]; then
    DEFAULT_PORT="$EXISTING"
    echo "Existing .env.local found. Current PORT=$DEFAULT_PORT"
  fi
fi

read -p "Port [$DEFAULT_PORT]: " USERPORT
PORT="${USERPORT:-$DEFAULT_PORT}"

# Validate
if ! [[ "$PORT" =~ ^[0-9]+$ ]]; then
  echo "[WARN] \"$PORT\" is not a number. Falling back to 3005."
  PORT=3005
fi
if [ "$PORT" -lt 1024 ]; then
  echo "[WARN] Ports under 1024 need root privileges. Falling back to 3005."
  PORT=3005
fi
if [ "$PORT" -gt 65535 ]; then
  echo "[WARN] Port must be under 65536. Falling back to 3005."
  PORT=3005
fi

cat > .env.local <<EOF
# AdForge configuration (generated by install.sh)
PORT=$PORT
ADFORGE_SYNC_PORT=3006
EOF

echo
echo "Saved PORT=$PORT to .env.local"
echo
echo "=================================================="
echo " Install complete."
echo "=================================================="
echo
echo "Next steps:"
echo "  1. Double-click  AdForge  on your Desktop  (or run: bash AdForge.command)"
echo "  2. Your browser opens to the AdForge launcher"
echo "  3. Click the orange Start button to boot the web app at:"
echo "       http://localhost:$PORT/"
echo "       http://adforge.localhost:$PORT/    (zero setup, works in all modern browsers)"
echo
echo "Want a prettier URL like  http://adforge.local:$PORT/  ?"
echo "  Run:  sudo bash scripts/set-domain.sh"
echo
echo "Your data lives in:"
echo "  $(pwd)/data/snapshot.json"
echo "Zip this folder to move AdForge + your work to another machine."
echo
